name: soaurl
description: A Url Shortener.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  firebase_analytics: ^8.1.1
  firebase_auth: ^1.3.0
  firebase_core: ^1.2.1
  firebase_crashlytics: ^2.0.5
  fl_chart: ^0.36.1
  flutter_slider_drawer: ^2.0.0
  get: ^4.1.4
  get_storage: ^2.0.2
  google_fonts: ^2.1.0
  google_mobile_ads: ^0.12.0
  google_sign_in: ^5.0.4
  intl: ^0.17.0
  pretty_qr_code: ^2.0.2
  url_launcher: ^6.0.6
  velocity_x: ^3.2.0
  websafe_svg: ^2.0.0
  receive_sharing_intent: ^1.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
